baseURL = "/wiki"
languageCode = "en-us"
title = "P(CC)^2 Wiki"
theme = "hugo-theme-learn"

[params]
editURL = "https://github.com/ArchWizard56/PCC-Squared-Wiki/tree/main/content/"
themeVariant = "pcc-green"
titleSeparator = "-"

[outputs]
home = [ "HTML", "RSS", "JSON"]
